#!/bin/sh
pipeline 
{
    agent any
    stages 
    {
      stage('Checkout Repo') {
          steps {
	          git credentialsId: 'Git-Credentials', url:'https://github.com/khushi1997n/phppipeline.git', branch: 'master'
          }
      }
      stage('Build'){
          steps{
                sh 'mv wp-config-sample.php wp-config.php'
       		sh 'sed -i "s|khushbooj|$host|g" wp-config.php'
       		sh 'sed -i "s|khushbooj|$username|g" wp-config.php'
       		sh 'sed -i "s|khushbooj|$pass|g" wp-config.php'
       		sh 'sed -i "s|khushbooj.cfdyrms3ajre.ap-south-1.rds.amazonaws.com|$endpoint|g" wp-config.php'
                sh 'sed -i "s|:3306||g" wp-config.php'
        	sh 'cat wp-config.php'
		}}
      stage('Depoly') {
          steps {
               sh 'sudo apt update -y'
               sh 'apt -qq install php libapache2-mod-php php-mysql -y'
               sh 'apt -qq install php-curl php-gd php-xml php-mbstring php-xmlrpc php-zip php-soap php-intl -y'
	       sh 'cd /var/www/html; git clone https://github.com/khushi1997n/phppipeline.git'
	       sh 'sudo chown -R www-data:www-data /var/www/html'
      }
    }
}
}


	
